//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.28 at 05:11:57 PM EAT 
//


package com.craftsoftware.retail;

import javax.xml.bind.annotation.XmlRegistry;

import com.dataaccesslayer.entity.Bill;
import com.dataaccesslayer.entity.Product;
import com.dataaccesslayer.entity.ProductCategory;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.craftsoftware.retail package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.craftsoftware.retail
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DeleteProductRequest }
     * 
     */
    public DeleteProductRequest createDeleteProductRequest() {
        return new DeleteProductRequest();
    }

    /**
     * Create an instance of {@link GetBillResponse }
     * 
     */
    public GetBillResponse createGetBillResponse() {
        return new GetBillResponse();
    }

    /**
     * Create an instance of {@link Bill }
     * 
     */
    public Bill createBill() {
        return new Bill();
    }

    /**
     * Create an instance of {@link DeleteBillResponse }
     * 
     */
    public DeleteBillResponse createDeleteBillResponse() {
        return new DeleteBillResponse();
    }

    /**
     * Create an instance of {@link GetProductRequest }
     * 
     */
    public GetProductRequest createGetProductRequest() {
        return new GetProductRequest();
    }

    /**
     * Create an instance of {@link UpdateProductRequest }
     * 
     */
    public UpdateProductRequest createUpdateProductRequest() {
        return new UpdateProductRequest();
    }

    /**
     * Create an instance of {@link Product }
     * 
     */
    public Product createProduct() {
        return new Product();
    }

    /**
     * Create an instance of {@link GetAllBillsRequest }
     * 
     */
    public GetAllBillsRequest createGetAllBillsRequest() {
        return new GetAllBillsRequest();
    }

    /**
     * Create an instance of {@link DeleteBillRequest }
     * 
     */
    public DeleteBillRequest createDeleteBillRequest() {
        return new DeleteBillRequest();
    }

    /**
     * Create an instance of {@link GetProductCategoryRequest }
     * 
     */
    public GetProductCategoryRequest createGetProductCategoryRequest() {
        return new GetProductCategoryRequest();
    }

    /**
     * Create an instance of {@link CreateProductCategoryRequest }
     * 
     */
    public CreateProductCategoryRequest createCreateProductCategoryRequest() {
        return new CreateProductCategoryRequest();
    }

    /**
     * Create an instance of {@link CreateProductCategory }
     * 
     */
    public CreateProductCategory createCreateProductCategory() {
        return new CreateProductCategory();
    }

    /**
     * Create an instance of {@link GetAllProductCategorysRequest }
     * 
     */
    public GetAllProductCategorysRequest createGetAllProductCategorysRequest() {
        return new GetAllProductCategorysRequest();
    }

    /**
     * Create an instance of {@link GetAllProductCategorysResponse }
     * 
     */
    public GetAllProductCategorysResponse createGetAllProductCategorysResponse() {
        return new GetAllProductCategorysResponse();
    }

    /**
     * Create an instance of {@link ProductCategory }
     * 
     */
    public ProductCategory createProductCategory() {
        return new ProductCategory();
    }

    /**
     * Create an instance of {@link GetBillRequest }
     * 
     */
    public GetBillRequest createGetBillRequest() {
        return new GetBillRequest();
    }

    /**
     * Create an instance of {@link UpdateProductResponse }
     * 
     */
    public UpdateProductResponse createUpdateProductResponse() {
        return new UpdateProductResponse();
    }

    /**
     * Create an instance of {@link UpdateProductCategoryResponse }
     * 
     */
    public UpdateProductCategoryResponse createUpdateProductCategoryResponse() {
        return new UpdateProductCategoryResponse();
    }

    /**
     * Create an instance of {@link CreateBillResponse }
     * 
     */
    public CreateBillResponse createCreateBillResponse() {
        return new CreateBillResponse();
    }

    /**
     * Create an instance of {@link GetAllProductsRequest }
     * 
     */
    public GetAllProductsRequest createGetAllProductsRequest() {
        return new GetAllProductsRequest();
    }

    /**
     * Create an instance of {@link DeleteProductCategoryResponse }
     * 
     */
    public DeleteProductCategoryResponse createDeleteProductCategoryResponse() {
        return new DeleteProductCategoryResponse();
    }

    /**
     * Create an instance of {@link CreateProductCategoryResponse }
     * 
     */
    public CreateProductCategoryResponse createCreateProductCategoryResponse() {
        return new CreateProductCategoryResponse();
    }

    /**
     * Create an instance of {@link GetProductResponse }
     * 
     */
    public GetProductResponse createGetProductResponse() {
        return new GetProductResponse();
    }

    /**
     * Create an instance of {@link UpdateBillResponse }
     * 
     */
    public UpdateBillResponse createUpdateBillResponse() {
        return new UpdateBillResponse();
    }

    /**
     * Create an instance of {@link GetAllProductsResponse }
     * 
     */
    public GetAllProductsResponse createGetAllProductsResponse() {
        return new GetAllProductsResponse();
    }

    /**
     * Create an instance of {@link UpdateProductCategoryRequest }
     * 
     */
    public UpdateProductCategoryRequest createUpdateProductCategoryRequest() {
        return new UpdateProductCategoryRequest();
    }

    /**
     * Create an instance of {@link CreateProductResponse }
     * 
     */
    public CreateProductResponse createCreateProductResponse() {
        return new CreateProductResponse();
    }

    /**
     * Create an instance of {@link CreateProductRequest }
     * 
     */
    public CreateProductRequest createCreateProductRequest() {
        return new CreateProductRequest();
    }

    /**
     * Create an instance of {@link CreateProduct }
     * 
     */
    public CreateProduct createCreateProduct() {
        return new CreateProduct();
    }

    /**
     * Create an instance of {@link CreateBillRequest }
     * 
     */
    public CreateBillRequest createCreateBillRequest() {
        return new CreateBillRequest();
    }

    /**
     * Create an instance of {@link CreateBill }
     * 
     */
    public CreateBill createCreateBill() {
        return new CreateBill();
    }

    /**
     * Create an instance of {@link UpdateBillRequest }
     * 
     */
    public UpdateBillRequest createUpdateBillRequest() {
        return new UpdateBillRequest();
    }

    /**
     * Create an instance of {@link GetProductCategoryResponse }
     * 
     */
    public GetProductCategoryResponse createGetProductCategoryResponse() {
        return new GetProductCategoryResponse();
    }

    /**
     * Create an instance of {@link GetAllBillsResponse }
     * 
     */
    public GetAllBillsResponse createGetAllBillsResponse() {
        return new GetAllBillsResponse();
    }

    /**
     * Create an instance of {@link DeleteProductResponse }
     * 
     */
    public DeleteProductResponse createDeleteProductResponse() {
        return new DeleteProductResponse();
    }

    /**
     * Create an instance of {@link DeleteProductCategoryRequest }
     * 
     */
    public DeleteProductCategoryRequest createDeleteProductCategoryRequest() {
        return new DeleteProductCategoryRequest();
    }

}
